-- Create roles and basic grants for HR personas
-- Assumptions: run as ACCOUNTADMIN or SECURITYADMIN for role creation

-- Roles
CREATE ROLE IF NOT EXISTS HR_ADMIN;
CREATE ROLE IF NOT EXISTS HR_ANALYST;

-- Warehouses (adjust sizes/names as needed)
CREATE WAREHOUSE IF NOT EXISTS WH_HR_XS WITH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

-- Grant usage on warehouse
GRANT USAGE ON WAREHOUSE WH_HR_XS TO ROLE HR_ADMIN;
GRANT USAGE ON WAREHOUSE WH_HR_XS TO ROLE HR_ANALYST;
GRANT USAGE ON WAREHOUSE WH_HR_XS TO ROLE PUBLIC;


