-- Create database and schemas for HR data
-- Assumptions: run as ACCOUNTADMIN or a role with CREATE DATABASE/SCHEMA

CREATE DATABASE IF NOT EXISTS HR;
USE DATABASE HR;

CREATE SCHEMA IF NOT EXISTS PII;      -- sensitive user attributes
CREATE SCHEMA IF NOT EXISTS ABSENCE;  -- absences facts with RAP


-- Ownership and usage grants
GRANT OWNERSHIP ON DATABASE HR TO ROLE HR_ADMIN COPY CURRENT GRANTS;
-- Note: PUBLIC can still query objects where explicitly granted
GRANT USAGE ON DATABASE HR TO ROLE HR_ANALYST;
GRANT USAGE ON DATABASE HR TO ROLE PUBLIC;

GRANT USAGE ON SCHEMA PII TO ROLE HR_ADMIN;
GRANT USAGE ON SCHEMA PII TO ROLE HR_ANALYST;
GRANT USAGE ON SCHEMA ABSENCE TO ROLE HR_ADMIN;
GRANT USAGE ON SCHEMA ABSENCE TO ROLE HR_ANALYST;
GRANT USAGE ON SCHEMA ABSENCE TO ROLE PUBLIC;

