-- Masking policies for PII columns
USE DATABASE HR;
USE SCHEMA PII;

-- Tags used to drive tag-based masking
CREATE OR REPLACE TAG TAG_PII_NAME COMMENT = 'Tag-based masking for name-like columns';
CREATE OR REPLACE TAG TAG_PII_EMAIL COMMENT = 'Tag-based masking for email columns';
CREATE OR REPLACE TAG TAG_PII_BIRTHDATE COMMENT = 'Tag-based masking for birthdate columns';

-- Name masking: show full to HR_ADMIN, partial to HR_ANALYST, null to others
CREATE OR REPLACE MASKING POLICY MP_PII_NAME_STR AS (val STRING) RETURNS STRING ->
  CASE
    WHEN IS_ROLE_IN_SESSION('ACCOUNTADMIN') OR IS_ROLE_IN_SESSION('HR_ADMIN') THEN val
    WHEN IS_ROLE_IN_SESSION('HR_ANALYST') THEN REGEXP_REPLACE(val, '(.)(.*)', '\1***')
    ELSE NULL
  END;

-- Email masking: show domain only to HR_ANALYST
CREATE OR REPLACE MASKING POLICY MP_PII_EMAIL_STR AS (val STRING) RETURNS STRING ->
  CASE
    WHEN IS_ROLE_IN_SESSION('ACCOUNTADMIN') OR IS_ROLE_IN_SESSION('HR_ADMIN') THEN val
    WHEN IS_ROLE_IN_SESSION('HR_ANALYST') THEN REGEXP_REPLACE(val, '^[^@]+', '***')
    ELSE NULL
  END;

-- Birthdate masking: show year only to HR_ANALYST
CREATE OR REPLACE MASKING POLICY MP_PII_BIRTHDATE_DATE AS (val DATE) RETURNS DATE ->
  CASE
    WHEN IS_ROLE_IN_SESSION('ACCOUNTADMIN') OR IS_ROLE_IN_SESSION('HR_ADMIN') THEN val
    WHEN IS_ROLE_IN_SESSION('HR_ANALYST') THEN TO_DATE(TO_CHAR(val, 'YYYY-01-01'))
    ELSE NULL
  END;

-- Bind masking policies to tags (tag-based masking)
ALTER TAG TAG_PII_NAME SET MASKING POLICY MP_PII_NAME_STR;
ALTER TAG TAG_PII_EMAIL SET MASKING POLICY MP_PII_EMAIL_STR;
ALTER TAG TAG_PII_BIRTHDATE SET MASKING POLICY MP_PII_BIRTHDATE_DATE;


