-- Create source tables and apply tag-based masking
USE DATABASE HR;

-- PII.USERS
CREATE OR REPLACE TABLE PII.USERS (
  USERNAME STRING,
  FIRSTNAME STRING,
  EMAIL STRING,
  BIRTHDATE DATE
);

-- Apply tags that drive masking (policies bound to tags in 03_masking_policies.sql)
ALTER TABLE PII.USERS MODIFY COLUMN USERNAME SET TAG HR.PII.TAG_PII_NAME = 'SENSITIVE';
ALTER TABLE PII.USERS MODIFY COLUMN FIRSTNAME SET TAG HR.PII.TAG_PII_NAME = 'SENSITIVE';
ALTER TABLE PII.USERS MODIFY COLUMN EMAIL SET TAG HR.PII.TAG_PII_EMAIL = 'SENSITIVE';
ALTER TABLE PII.USERS MODIFY COLUMN BIRTHDATE SET TAG HR.PII.TAG_PII_BIRTHDATE = 'SENSITIVE';

-- Object grants for PII.USERS
GRANT SELECT ON TABLE PII.USERS TO ROLE HR_ADMIN;
GRANT SELECT ON TABLE PII.USERS TO ROLE HR_ANALYST;

-- ABSENCE.ABSENCES
CREATE OR REPLACE TABLE ABSENCE.ABSENCES (
  USERNAME STRING,
  START_DATE DATE,
  END_DATE DATE,
  REASON STRING
);

-- Object grants for ABSENCE.ABSENCES (RAP further restricts row visibility)
GRANT SELECT ON TABLE ABSENCE.ABSENCES TO ROLE HR_ADMIN;
GRANT SELECT ON TABLE ABSENCE.ABSENCES TO ROLE PUBLIC;


-- Manager mapping: employee -> manager username
CREATE OR REPLACE TABLE ABSENCE.MANAGER_MAP (
  EMPLOYEE_USERNAME STRING,
  MANAGER_USERNAME STRING
);

-- Object grants for ABSENCE.MANAGER_MAP
GRANT SELECT ON TABLE ABSENCE.MANAGER_MAP TO ROLE HR_ADMIN;




