USE DATABASE HR;
USE SCHEMA ABSENCE;

-- Row Access Policy for ABSENCE.ABSENCES
-- Access rules:
--  - Admins (ACCOUNTADMIN, HR_ADMIN): all rows
--  - Employee self-access: USERNAME = CURRENT_USER()
--  - Employee (manager) access: rows for direct reports per ABSENCE.MANAGER_MAP
CREATE OR REPLACE ROW ACCESS POLICY RAP_ABSENCES AS (USERNAME STRING) RETURNS BOOLEAN ->
  CASE
    WHEN IS_ROLE_IN_SESSION('ACCOUNTADMIN') OR IS_ROLE_IN_SESSION('HR_ADMIN') THEN TRUE
    WHEN UPPER(USERNAME) = UPPER(CURRENT_USER()) THEN TRUE
    WHEN EXISTS (
      SELECT 1
      FROM HR.ABSENCE.MANAGER_MAP m
      WHERE m.EMPLOYEE_USERNAME = USERNAME
        AND UPPER(m.MANAGER_USERNAME) = UPPER(CURRENT_USER())
    ) THEN TRUE
    ELSE FALSE
  END;

-- Attach the policy to the table on the USERNAME column
ALTER TABLE HR.ABSENCE.ABSENCES ADD ROW ACCESS POLICY RAP_ABSENCES ON (USERNAME);


