-- Create three Snowflake users for testing access scenarios
-- Run as SECURITYADMIN

-- Users: admin, analyst, and public-role employees
CREATE OR REPLACE USER U_HR_ADMIN PASSWORD='Password123!' DEFAULT_ROLE=HR_ADMIN DEFAULT_WAREHOUSE=WH_HR_XS MUST_CHANGE_PASSWORD=FALSE;
CREATE OR REPLACE USER U_HR_ANALYST PASSWORD='Password123!' DEFAULT_ROLE=HR_ANALYST DEFAULT_WAREHOUSE=WH_HR_XS MUST_CHANGE_PASSWORD=FALSE;
CREATE OR REPLACE USER JDOE PASSWORD='Password123!' DEFAULT_ROLE=PUBLIC DEFAULT_WAREHOUSE=WH_HR_XS MUST_CHANGE_PASSWORD=FALSE;
CREATE OR REPLACE USER ASMITH PASSWORD='Password123!' DEFAULT_ROLE=PUBLIC DEFAULT_WAREHOUSE=WH_HR_XS MUST_CHANGE_PASSWORD=FALSE;
CREATE OR REPLACE USER BCHEN PASSWORD='Password123!' DEFAULT_ROLE=PUBLIC DEFAULT_WAREHOUSE=WH_HR_XS MUST_CHANGE_PASSWORD=FALSE;
CREATE OR REPLACE USER DLEE PASSWORD='Password123!' DEFAULT_ROLE=PUBLIC DEFAULT_WAREHOUSE=WH_HR_XS MUST_CHANGE_PASSWORD=FALSE;

-- Grant roles
GRANT ROLE HR_ADMIN TO USER U_HR_ADMIN;
GRANT ROLE HR_ANALYST TO USER U_HR_ANALYST;



